import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { trpc } from "@/lib/trpc";
import { cn } from "@/lib/utils";
import { useMemo } from "react";
import { useLocation } from "wouter";
import { AlertCircle, CheckCircle2, ChevronLeft, CircleHelp, Cookie, ExternalLink, KeyRound, RefreshCw, ShieldCheck, XCircle } from "lucide-react";

function CheckRow({ label, detail, ok, neutral = false }: { label: string; detail: string; ok: boolean; neutral?: boolean }) {
  return <div className="flex items-start gap-3 rounded-xl bg-[#f1f3ea] p-3 dark:bg-[#202a21]">{neutral ? <CircleHelp className="mt-0.5 h-4 w-4 shrink-0 text-[#899386]" /> : ok ? <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-[#6f922d]" /> : <XCircle className="mt-0.5 h-4 w-4 shrink-0 text-[#c85c6b]" />}<div className="min-w-0"><p className="text-xs font-medium">{label}</p><p className="mt-1 break-words text-[11px] leading-5 text-[#899386]">{detail}</p></div></div>;
}

export default function OAuthDiagnostics() {
  const [, setLocation] = useLocation();
  const authQuery = trpc.auth.diagnostics.useQuery(undefined, { retry: false, refetchOnWindowFocus: false });
  const authMeQuery = trpc.auth.me.useQuery(undefined, { retry: false, refetchOnWindowFocus: false });
  const diagnostics = authQuery.data;
  const queryError = useMemo(() => {
    const params = new URLSearchParams(window.location.search);
    return params.get("reason") || params.get("error_description") || params.get("error") || null;
  }, []);
  const refreshAll = async () => {
    await Promise.all([authQuery.refetch(), authMeQuery.refetch()]);
  };
  const sessionHealthy = Boolean(diagnostics?.sessionValid && diagnostics.userFound && authMeQuery.data);
  const sessionDetail = diagnostics?.sessionCookiePresent ? (diagnostics.sessionValid ? "Подписанная session cookie действительна" : "Cookie найдена, но подпись JWT недействительна или срок истёк") : diagnostics?.bearerSessionPresent ? "Используется Authorization: Bearer session" : "Активная session cookie не найдена";
  const providerDetail = diagnostics?.provider ? `Текущий провайдер: ${diagnostics.provider}` : "Провайдер не определён: пользователь не авторизован";
  const reasonLabel: Record<string, string> = { discord_state: "Discord state cookie не совпала или истекла", discord_config: "Discord OAuth credentials не настроены на сервере", discord_callback: "Discord callback не смог завершить token exchange или user lookup" };

  return <div className="soft-grid min-h-screen bg-[#f4f1e8] px-4 py-6 dark:bg-[#111713] sm:px-6 lg:px-10 lg:py-9"><div className="mx-auto max-w-[1100px] space-y-6"><Button variant="ghost" onClick={() => setLocation("/settings")} className="-ml-3 h-9 rounded-lg text-xs text-[#6f7c6d] hover:bg-[#e5e8db] dark:text-[#aab8a4] dark:hover:bg-[#202a21]"><ChevronLeft className="mr-1.5 h-4 w-4" />Назад в настройки</Button><section className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mono mb-2 text-[10px] uppercase tracking-[0.18em] text-[#8b9586]">System / auth diagnostics</p><h1 className="display-title text-3xl tracking-[-0.06em] sm:text-4xl">Диагностика авторизации</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#788374] dark:text-[#a4b0a1]">Проверь состояние локальной сессии и Discord callback без отображения токенов или паролей.</p></div><Badge className={cn("w-fit rounded-md px-3 py-1.5 text-[11px]", authQuery.isLoading ? "bg-[#fff4d8] text-[#9e741d] dark:bg-[#3d321c] dark:text-[#ffd36b]" : sessionHealthy ? "bg-[#effbd6] text-[#638823] dark:bg-[#293b22] dark:text-[#c5ff3f]" : "bg-[#ffe5e8] text-[#ad4c5a] dark:bg-[#3b2226] dark:text-[#ff9daa]")}>{authQuery.isLoading ? "Проверка…" : sessionHealthy ? "Сессия активна" : "Нет активной сессии"}</Badge></section>

{queryError && <Card className="rounded-[20px] border-[#f0b7bf] bg-[#fff5f6] dark:border-[#5d3037] dark:bg-[#2b1c20]"><CardContent className="flex items-start gap-3 p-4"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-[#c85c6b]" /><div><p className="text-xs font-semibold text-[#ad4c5a] dark:text-[#ff9daa]">Последняя ошибка входа</p><p className="mt-1 text-xs text-[#ad4c5a] dark:text-[#ffb4be]">{reasonLabel[queryError] || queryError}</p></div></CardContent></Card>}

<div className="grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><Card className="rounded-[24px] border-[#dfe2d6] bg-[#fffdf7] panel-shadow dark:border-white/10 dark:bg-[#171f19]"><CardHeader className="px-5 pb-3 pt-5 sm:px-6"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#effbd6] text-[#6c9626] dark:bg-[#293b22] dark:text-[#c5ff3f]"><ShieldCheck className="h-5 w-5" /></div><div><CardTitle className="text-base">Состояние сессии</CardTitle><p className="mt-1 text-xs text-[#899386]">Проверка выполняется на сервере</p></div></div></CardHeader><CardContent className="space-y-3 px-5 pb-5 sm:px-6 sm:pb-6"><CheckRow label="auth.me" ok={Boolean(authMeQuery.data)} neutral={!authMeQuery.data && !authMeQuery.error} detail={authMeQuery.data ? `Авторизован как ${authMeQuery.data.name || authMeQuery.data.email || "пользователь"}` : authMeQuery.error ? "auth.me недоступен" : "Пользователь не авторизован"} /><CheckRow label="Подписанная сессия" ok={Boolean(diagnostics?.sessionValid)} neutral={!diagnostics?.sessionCookiePresent && !diagnostics?.bearerSessionPresent} detail={sessionDetail} /><CheckRow label="User mapping" ok={Boolean(diagnostics?.userFound)} neutral={!diagnostics?.sessionValid} detail={diagnostics?.userFound ? providerDetail : "Сессия не сопоставлена с пользователем в базе данных"} /><CheckRow label="Discord state cookie" ok={Boolean(diagnostics?.discordStateCookiePresent)} neutral detail={diagnostics?.discordStateCookiePresent ? "State cookie активна — callback может завершить OAuth" : "State cookie отсутствует вне активного Discord login flow"} /><Button variant="outline" onClick={() => void refreshAll()} disabled={authQuery.isFetching || authMeQuery.isFetching} className="mt-2 h-10 w-full rounded-xl border-[#dfe2d6] text-xs dark:border-white/10"><RefreshCw className={cn("mr-2 h-3.5 w-3.5", (authQuery.isFetching || authMeQuery.isFetching) && "animate-spin")} />Повторить проверку</Button></CardContent></Card>

<Card className="rounded-[24px] border-[#dfe2d6] bg-[#fffdf7] panel-shadow dark:border-white/10 dark:bg-[#171f19]"><CardHeader className="px-5 pb-3 pt-5 sm:px-6"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf1ff] text-[#607dd8] dark:bg-[#26304e] dark:text-[#a8baff]"><KeyRound className="h-5 w-5" /></div><div><CardTitle className="text-base">Параметры Discord OAuth</CardTitle><p className="mt-1 text-xs text-[#899386]">Секреты не показываются в браузере</p></div></div></CardHeader><CardContent className="space-y-3 px-5 pb-5 sm:px-6 sm:pb-6"><div><p className="mb-1 text-[10px] uppercase tracking-wide text-[#899386]">Callback URL</p><p className="break-all rounded-lg bg-[#f1f3ea] p-2.5 font-mono text-[10px] text-[#637061] dark:bg-[#202a21] dark:text-[#b1beb0]">{window.location.origin}/api/auth/discord/callback</p></div><Separator /><div><p className="mb-1 text-[10px] uppercase tracking-wide text-[#899386]">Authorize endpoint</p><p className="break-all rounded-lg bg-[#f1f3ea] p-2.5 font-mono text-[10px] text-[#637061] dark:bg-[#202a21] dark:text-[#b1beb0]">https://discord.com/oauth2/authorize</p></div><div><p className="mb-1 text-[10px] uppercase tracking-wide text-[#899386]">Server configuration</p><p className="rounded-lg bg-[#f1f3ea] p-2.5 text-[10px] text-[#637061] dark:bg-[#202a21] dark:text-[#b1beb0]">Client credentials: {diagnostics ? "получены сервером" : "проверка не завершена"}</p></div></CardContent></Card></div>

<Card className="rounded-[24px] border-[#dfe2d6] bg-[#fffdf7] panel-shadow dark:border-white/10 dark:bg-[#171f19]"><CardHeader className="px-5 pb-3 pt-5 sm:px-6"><CardTitle className="text-base">Если Discord-вход не завершается</CardTitle></CardHeader><CardContent className="grid gap-3 px-5 pb-5 text-xs leading-5 text-[#788374] sm:grid-cols-3 sm:px-6 sm:pb-6"><div className="rounded-xl bg-[#f1f3ea] p-3 dark:bg-[#202a21]"><Cookie className="mb-2 h-4 w-4 text-[#799d32]" /><p className="font-medium text-[#151a16] dark:text-[#e7efe5]">Cookies</p><p className="mt-1">Разреши cookies для панели и Discord. State cookie используется только на время OAuth flow.</p></div><div className="rounded-xl bg-[#f1f3ea] p-3 dark:bg-[#202a21]"><ExternalLink className="mb-2 h-4 w-4 text-[#799d32]" /><p className="font-medium text-[#151a16] dark:text-[#e7efe5]">Redirect URI</p><p className="mt-1">В Discord Developer Portal должен быть добавлен callback URL, показанный выше, без лишнего слеша.</p></div><div className="rounded-xl bg-[#f1f3ea] p-3 dark:bg-[#202a21]"><AlertCircle className="mb-2 h-4 w-4 text-[#799d32]" /><p className="font-medium text-[#151a16] dark:text-[#e7efe5]">Секреты</p><p className="mt-1">DISCORD_CLIENT_ID и DISCORD_CLIENT_SECRET должны быть заданы в server environment, не в клиенте.</p></div></CardContent></Card></div></div>;
}
